"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .drinks import Drinks
from .sdkconfiguration import SDKConfiguration

class Menu:
    drinks: Drinks
    sdk_configuration: SDKConfiguration

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.drinks = Drinks(self.sdk_configuration)
        
    