openapi: 3.1.0
info:
  title: The Speakeasy Bar
  version: 1.0.0
servers:
  - url: https://speakeasy.bar
    description: The production server
security:
  - apiKey: []
x-speakeasy-name-override:
  - operationId: ^list_.*
    methodNameOverride: list
paths:
  /drinks:
    get:
      tags:
        - menu
      x-speakeasy-group: menu.drinks
      operationId: list_drinks_v2_get
      x-speakeasy-usage-example: true
      summary: Get a list of drinks
      responses:
        "200":
          description: A list of drinks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drink"
components:
  schemas:
    Drink:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
  securitySchemes:
    apiKey:
      type: apiKey
      name: Authorization
      in: header
      x-speakeasy-example: "<YOUR_API_KEY>"

